name: Setup repository
on:
  push:
    paths:
      - cookiecutter.json

# To enforce write permissions for GITHUB_TOKEN, by default all scopes are read-only,
# it prevents from pushing to the repository.
permissions:
  actions: write
  contents: write

jobs:
  setup:
    name: Reinitialize repository
    if: github.run_number != 1
    runs-on: ubuntu-latest
    env:
      REPO_SETUP_TOKEN: ${{ secrets.REPO_SETUP_TOKEN }}
    steps:
      - name: Do not run scaffolding on template repository
        shell: bash
        # This workflow runs when the `cookiecutter.json` file is modified.
        # This is the trick to re-init a repository, but we don't want to
        # run this action if this file is modified in the origin template repository.
        #
        # Using the GitHub rest API allows us to identify if the current repository
        # is a template repository or not.
        run: |
          curl --silent -X GET \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.baptiste-preview+json" \
            https://api.github.com/repos/$GITHUB_REPOSITORY \
            | jq --exit-status '.is_template == false';

      - uses: actions/checkout@v2
        with:
          # Committing workflow files using the regular GITHUB_TOKEN will fail with 
          # `Git Error: Refusing to allow a GitHub App to create or update workflow without workflows permission`.
          # This is by design to prevent third-parties from adding malicious workflow files.
          #
          # Generate a new personal access token with the workflow `scope` does the trick.
          # Checkout my blog post https://stefanbuck.com/blog for alternative options
          token: ${{ env.REPO_SETUP_TOKEN || secrets.GITHUB_TOKEN }}

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install cookiecutter

      - name: Get repository information
        id: repo-info
        uses: actions/github-script@v6
        with:
          script: |
            const repo = await github.rest.repos.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            return {
              repo_owner: context.repo.owner,
              repo_name: context.repo.repo,
              repo_url: repo.data.html_url,
              repo_description: repo.data.description || ""
              repo_license: repo.data.license.spdx_id || ""
            };

      - name: Update placeholders in cookiecutter.json
        env:
          REPO_OWNER: ${{ steps.repo-info.outputs.repo_owner }}
          REPO_NAME: ${{ steps.repo-info.outputs.repo_name }}
          REPO_URL: ${{ steps.repo-info.outputs.repo_url }}
          REPO_DESCRIPTION: ${{ steps.repo-info.outputs.repo_description }}
          REPO_LICENSE: ${{ steps.repo-info.outputs.repo_license }}
        run: |
          sed -i "s|{{github.username}}|$REPO_OWNER|g" cookiecutter.json
          sed -i "s|{{github.repo_url}}|$REPO_URL|g" cookiecutter.json
          sed -i "s|{{github.repo_name}}|$REPO_NAME|g" cookiecutter.json
          sed -i "s|{{github.repo_description}}|$REPO_DESCRIPTION|g" cookiecutter.json
          sed -i "s|{{github.repo_license}}|$REPO_LICENSE|g" cookiecutter.json

      - name: Scaffolding repository
        # cookiecutter is command-line utility to create projects from templates
        # https://github.com/cookiecutter/cookiecutter
        #
        # --no-input      Do not prompt for parameters and only use
        #                 cookiecutter.json file content
        #
        # --output-dir    Where to output the generated project dir into
        run: cookiecutter . --no-input --output-dir ./cookiecutter-temp

      - name: Prepare root directory
        shell: bash
        # Remove all files and folder exepct .git/, .github/ and cookiecutter-temp/
        run: |
          find ./ -maxdepth 1 \
          ! -name '.git' \
          ! -name '.github' \
          ! -name 'cookiecutter-temp' \
          ! -name '.' \
          ! -exec rm -rf {} +
      
      - name: Remove setup-repository.yml
        shell: bash
        # Remove this workflow file
        run: rm -rf ./.github/workflows/setup-repository.yml

      - name: Remove template-only sections from build.yml
        run: |
          sed -i '/#<template-ci>/,/#<\/template-ci>/d' .github/workflows/build.yml

      - name: Move files to root
        shell: bash
        # The cookiecutter-temp/ folder contains a single folder which is the
        # generated project by cookiecutter. We want to move all the project
        # files into the root directory so we can reinitialize git in the next step
        run: |
          rsync -r ./cookiecutter-temp/*/ . && \
          rm -rf ./cookiecutter-temp/

      - name: Reinitialize git repository
        shell: bash
        # Reinitialize git after scaffolding this repository.
        # We use `git checkout --orphan` to create a branch in a git init-like state.
        # By force pushing this as `main` we end up with a new clean git history.
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com" && \
          git config --global user.name "github-actions[bot]" && \
          git checkout --orphan temp-branch && \
          git add . && \
          git commit -m 'Initial commit' && \
          git push origin temp-branch:main -f

      - name: Remove secret REPO_SETUP_TOKEN
        # After re-initializing the repository, we can remove the `REPO_SETUP_TOKEN` secret.
        shell: bash
        if: ${{ env.REPO_SETUP_TOKEN }}
        run: |
          curl \
            -X DELETE --fail \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ env.REPO_SETUP_TOKEN }}" \
            https://api.github.com/repos/$GITHUB_REPOSITORY/actions/secrets/REPO_SETUP_TOKEN
